### ISSUE TITLE
feat: use fastcache

### ISSUE THREAD

**Issue by 0Tech** [Finschia/cosmos-sdk#14]

**Comment by tkxkd0159** [comment]
Finschia/finschia-sdk#164 (related to Finschia/finschia-sdk#184)
cosmos-skd doesn't use cachekv from store/v2(#18150) and use rocksdb's internal cache. But v0.50 still use store/v1. So we need to benchmark if `fastcache` really improve the performance. If there is no big changes, we should use original cache(Hashicorp's `Adaptive Replacement Cache`) instead
