### ISSUE TITLE
chore: bump codecov-action up from 1.2.1 to 1.5.0 - Triage finschia-sdk#181

### ISSUE THREAD

**Issue by 0Tech** [Finschia/cosmos-sdk#16]

**Comment by jaeseung-bae** [comment]
##### Desc
- bump Coverage github action
##### Suggestion(Abandon/Maintain/Submit) 
- Abandon: outdated
##### Links
- https://github.com/Finschia/finschia-sdk/pull/181

**Comment by jaeseung-bae** [comment]
todo: check anything in script is still necessary

**Comment by jaeseung-bae** [comment]
> todo: check anything in script is still necessary

Couldn't find any to keep
