### ISSUE TITLE
chore: Allow codecov job to filter unnecessary files - Triage finschia-sdk#197

### ISSUE THREAD

**Issue by 0Tech** [Finschia/cosmos-sdk#21]

**Comment by jaeseung-bae** [comment]
##### Desc
- filter some files from calculation of code coverage
##### Suggestion(Abandon/Maintain/Submit) 
- Abandon: outdated
##### Links
- https://github.com/Finschia/finschia-sdk/pull/197

**Comment by jaeseung-bae** [comment]
couldn't find anything to keep
