### ISSUE TITLE
chore: add script initializing simd

### ISSUE THREAD

**Issue by 0Tech** [Finschia/cosmos-sdk#3]

**Comment by ulbqb** [comment]
- PR - Finschia/finschia-sdk#110
- Type - CI
- Desc - 
  1. Added a script initializing simd node
  2. Use goleveldb for build_tags by default 
- Decision
  1. Abandon -  Simillar script already exists in https://github.com/cosmos/cosmos-sdk/blob/v0.50.2/Makefile#L188-L191.
  2. ~~Maintain~~ Abandon

**Comment by jaeseung-bae** [comment]
`Use goleveldb for build_tags by default` relates to #6
