### ISSUE TITLE
test: decrease sim test time - Triage finschia-sdk#350

### ISSUE THREAD

**Issue by 0Tech** [Finschia/cosmos-sdk#36]

**Comment by jaeseung-bae** [comment]
##### Desc
- test: decrease sim test time by smaller parameter values
##### Suggestion(Abandon/Maintain/Submit) 
- Abandon
  - No significant improvement when I checked the last two months 
  - No rational found
    - Not sure it's okay to reduce parameter for the tests
##### Links
- https://github.com/Finschia/finschia-sdk/pull/350
