### ISSUE TITLE
fix: fix the data race problem in `TestQueryABCIHeight`

### ISSUE THREAD

**Issue by 0Tech** [Finschia/cosmos-sdk#49]

**Comment by tkxkd0159** [comment]
Finschia/finschia-sdk#565
Upstream code has no problem with previous code. So we should check if we need to apply this when we apply v0.5x

ref. https://github.com/cosmos/cosmos-sdk/blob/2587e756c110b78d0719cc85b0feb12afefa4890/client/rpc/rpc_test.go#L59
