### ISSUE TITLE
fix the bug not setting `iavl-cache-size` value of `app.toml` - Triage finschia-sdk#679

### ISSUE THREAD

**Issue by 0Tech** [Finschia/cosmos-sdk#56]

**Comment by jaeseung-bae** [comment]
##### Desc
- Set iavl cache parameter while `newApp()` and change `DefaultIAVLCacheSize` value
##### Suggestion(Abandon/Maintain/Submit)
- Maintain: finschia-sdk
##### Links
- https://github.com/Finschia/finschia-sdk/pull/679

**Comment by jaeseung-bae** [comment]
TODO: Check for abandon if this is no longer necessary after v0.50.2

**Comment by jaeseung-bae** [comment]
> TODO: Check for abandon if this is no longer necessary after v0.50.2

Setting iavl-cache-size is unnecessary(https://github.com/cosmos/cosmos-sdk/pull/13107).
But we may need changed default size `128MB -> // default 64MB`

**Comment by jaeseung-bae** [comment]
We have a default configuration which is 64MB.
