### ISSUE TITLE
fix: DB_BACKEND configuration - Triage finschia-sdk#136

### ISSUE THREAD

**Issue by 0Tech** [Finschia/cosmos-sdk#6]

**Comment by jaeseung-bae** [comment]
##### Desc
- build: set goleveldb as default
##### Suggestion(Abandon/Maintain/Submit) 
- Abandon: no effect anymore
  - It's built with goleveldb without this PR
  - Tests are fine without this PR
##### Links
- https://github.com/Finschia/finschia-sdk/pull/136
