### ISSUE TITLE
fix: modify default coin type, default address prefix

### ISSUE THREAD

**Issue by 0Tech** [Finschia/cosmos-sdk#8]

**Comment by ulbqb** [comment]
- PR - Finschia/finschia-sdk#140
- Type - Core
- Desc - modified default coin type(438; link coin) and default address prefix(link)
- Decision - Abandon
  - This handling should be done in app by using [these functions](https://github.com/cosmos/cosmos-sdk/blob/v0.50.2/types/address.go#L26-L36).
