### ISSUE TITLE
refactor: change the proof.proto path to third_party/proto/confio - Triage finschia-sdk#1037

### ISSUE THREAD

**Issue by 0Tech** [Finschia/cosmos-sdk#82]
The subject of the triage:
- Finschia/finschia-sdk#1037

**Comment by jaeseung-bae** [comment]
##### Desc
- Change path of proof.proto path
##### Suggestion(Abandon/Maintain/Submit) 
- Abandon: No need
##### Links
- https://github.com/Finschia/finschia-sdk/pull/1037
