### ISSUE TITLE
docs: document default events - Triage finschia-sdk#1081

### ISSUE THREAD

**Issue by 0Tech** [Finschia/cosmos-sdk#86]
The subject of the triage:
- Finschia/finschia-sdk#1081

**Comment by jaeseung-bae** [comment]
##### Desc
- docs: document default events
##### Suggestion(Abandon/Maintain/Submit) 
- ~Maintain: finschia-sdk~
- Abandon: backport cosmos/cosmos-sdk#13532
##### Links
- https://github.com/Finschia/finschia-sdk/pull/1081

**Comment by jaeseung-bae** [comment]
todo: check upstream for duplication

**Comment by jaeseung-bae** [comment]
> todo: check upstream for duplication

backport cosmos/cosmos-sdk#13532
